# Site settings
title: Scala University
email: scalauniversity@gmail.com
description: "Scala University is an idea of continuous learning/teaching Scala in the form of free workshops driven by developers at ThoughtWorks, Pune who are passionate Scala users."
baseurl: ""
url: "http://scalauniversity.org"
twitter_username: scalauniversity
github_username:  scalauniversity

# Build settings
markdown: kramdown
permalink: pretty
